var _i_t__03_json_persister_persistence_api_consideration_8cs =
[
    [ "IntegrationTests.Persistence.IT_03JsonPersisterPersistenceApiConsideration", "class_integration_tests_1_1_persistence_1_1_i_t__03_json_persister_persistence_api_consideration.html", "class_integration_tests_1_1_persistence_1_1_i_t__03_json_persister_persistence_api_consideration" ]
];