var annotated_dup =
[
    [ "IntegrationTests", "namespace_integration_tests.html", [
      [ "CalculateUtility", "namespace_integration_tests_1_1_calculate_utility.html", [
        [ "IT_01ConsiderationUSAverage", "class_integration_tests_1_1_calculate_utility_1_1_i_t__01_consideration_u_s_average.html", "class_integration_tests_1_1_calculate_utility_1_1_i_t__01_consideration_u_s_average" ],
        [ "IT_ConsiderationUsAverageAiContextDecision", "class_integration_tests_1_1_calculate_utility_1_1_i_t___consideration_us_average_ai_context_decision.html", "class_integration_tests_1_1_calculate_utility_1_1_i_t___consideration_us_average_ai_context_decision" ],
        [ "IT_ConsiderationUsAverageAiContextDecisionBucket", "class_integration_tests_1_1_calculate_utility_1_1_i_t___consideration_us_average_ai_context_decision_bucket.html", "class_integration_tests_1_1_calculate_utility_1_1_i_t___consideration_us_average_ai_context_decision_bucket" ],
        [ "IT_ConsiderationUsAverageAiContextDecisionBucketUcsHighest", "class_integration_tests_1_1_calculate_utility_1_1_i_t___consideration_us_average_ai_context_decision_bucket_ucs_highest.html", "class_integration_tests_1_1_calculate_utility_1_1_i_t___consideration_us_average_ai_context_decision_bucket_ucs_highest" ],
        [ "IT_ConsiderationUsAverageAiContextDecisionBucketUcsHighestDSE", "class_integration_tests_1_1_calculate_utility_1_1_i_t___consideration_us_average_ai_context_decision_bucket_ucs_highest_d_s_e.html", "class_integration_tests_1_1_calculate_utility_1_1_i_t___consideration_us_average_ai_context_decision_bucket_ucs_highest_d_s_e" ]
      ] ],
      [ "Persistence", "namespace_integration_tests_1_1_persistence.html", [
        [ "IT_01JsonPersisterPersistenceApiAgentAction", "class_integration_tests_1_1_persistence_1_1_i_t__01_json_persister_persistence_api_agent_action.html", "class_integration_tests_1_1_persistence_1_1_i_t__01_json_persister_persistence_api_agent_action" ],
        [ "IT_02JsonPersisterPersistenceApiResponseCurve", "class_integration_tests_1_1_persistence_1_1_i_t__02_json_persister_persistence_api_response_curve.html", "class_integration_tests_1_1_persistence_1_1_i_t__02_json_persister_persistence_api_response_curve" ],
        [ "IT_03JsonPersisterPersistenceApiConsideration", "class_integration_tests_1_1_persistence_1_1_i_t__03_json_persister_persistence_api_consideration.html", "class_integration_tests_1_1_persistence_1_1_i_t__03_json_persister_persistence_api_consideration" ],
        [ "IT_04JsonPersisterPersistenceApiDecision", "class_integration_tests_1_1_persistence_1_1_i_t__04_json_persister_persistence_api_decision.html", "class_integration_tests_1_1_persistence_1_1_i_t__04_json_persister_persistence_api_decision" ]
      ] ],
      [ "Restoring", "namespace_integration_tests_1_1_restoring.html", [
        [ "IT_RestoreAbleRestoreStateAllUaiObjects", "class_integration_tests_1_1_restoring_1_1_i_t___restore_able_restore_state_all_uai_objects.html", "class_integration_tests_1_1_restoring_1_1_i_t___restore_able_restore_state_all_uai_objects" ]
      ] ]
    ] ],
    [ "Mocks", "namespace_mocks.html", [
      [ "Mock_Agent", "class_mocks_1_1_mock___agent.html", "class_mocks_1_1_mock___agent" ],
      [ "Mock_AgentAction", "class_mocks_1_1_mock___agent_action.html", "class_mocks_1_1_mock___agent_action" ],
      [ "Mock_Bucket", "class_mocks_1_1_mock___bucket.html", "class_mocks_1_1_mock___bucket" ],
      [ "Mock_ConsiderationSimple", "class_mocks_1_1_mock___consideration_simple.html", "class_mocks_1_1_mock___consideration_simple" ],
      [ "Mock_Decision", "class_mocks_1_1_mock___decision.html", "class_mocks_1_1_mock___decision" ],
      [ "Mock_IPersister", "class_mocks_1_1_mock___i_persister.html", "class_mocks_1_1_mock___i_persister" ],
      [ "Mock_ResponseCurve", "class_mocks_1_1_mock___response_curve.html", "class_mocks_1_1_mock___response_curve" ],
      [ "Mock_ResponseCurve_IT", "class_mocks_1_1_mock___response_curve___i_t.html", "class_mocks_1_1_mock___response_curve___i_t" ],
      [ "Mock_ResponseFunction", "class_mocks_1_1_mock___response_function.html", "class_mocks_1_1_mock___response_function" ],
      [ "Mock_Uai", "class_mocks_1_1_mock___uai.html", "class_mocks_1_1_mock___uai" ],
      [ "Mock_UtilityContainerSelector", "class_mocks_1_1_mock___utility_container_selector.html", "class_mocks_1_1_mock___utility_container_selector" ],
      [ "Stub_Consideration_IT", "class_mocks_1_1_stub___consideration___i_t.html", "class_mocks_1_1_stub___consideration___i_t" ],
      [ "Stub_Consideration_UT", "class_mocks_1_1_stub___consideration___u_t.html", "class_mocks_1_1_stub___consideration___u_t" ]
    ] ],
    [ "Models", "namespace_models.html", [
      [ "SequenceExecutionTimeModel", "class_models_1_1_sequence_execution_time_model.html", "class_models_1_1_sequence_execution_time_model" ]
    ] ],
    [ "Services", "namespace_services.html", [
      [ "Scorers", "namespace_services_1_1_scorers.html", [
        [ "UtilityScorer", "namespace_services_1_1_scorers_1_1_utility_scorer.html", [
          [ "USHighestScore", "class_services_1_1_scorers_1_1_utility_scorer_1_1_u_s_highest_score.html", "class_services_1_1_scorers_1_1_utility_scorer_1_1_u_s_highest_score" ],
          [ "USLowestScore", "class_services_1_1_scorers_1_1_utility_scorer_1_1_u_s_lowest_score.html", "class_services_1_1_scorers_1_1_utility_scorer_1_1_u_s_lowest_score" ]
        ] ]
      ] ]
    ] ],
    [ "Tests", "namespace_tests.html", [
      [ "Editor", "namespace_tests_1_1_editor.html", [
        [ "UnitTests", "namespace_tests_1_1_editor_1_1_unit_tests.html", [
          [ "TestHelpers", "class_tests_1_1_editor_1_1_unit_tests_1_1_test_helpers.html", null ]
        ] ]
      ] ]
    ] ],
    [ "UniRx", "namespace_uni_rx.html", [
      [ "Diagnostics", "namespace_uni_rx_1_1_diagnostics.html", [
        [ "LogEntry", "struct_uni_rx_1_1_diagnostics_1_1_log_entry.html", "struct_uni_rx_1_1_diagnostics_1_1_log_entry" ],
        [ "Logger", "class_uni_rx_1_1_diagnostics_1_1_logger.html", "class_uni_rx_1_1_diagnostics_1_1_logger" ],
        [ "ObservableLogger", "class_uni_rx_1_1_diagnostics_1_1_observable_logger.html", "class_uni_rx_1_1_diagnostics_1_1_observable_logger" ],
        [ "UnityDebugSink", "class_uni_rx_1_1_diagnostics_1_1_unity_debug_sink.html", "class_uni_rx_1_1_diagnostics_1_1_unity_debug_sink" ]
      ] ],
      [ "Examples", "namespace_uni_rx_1_1_examples.html", [
        [ "Enemy", "class_uni_rx_1_1_examples_1_1_enemy.html", "class_uni_rx_1_1_examples_1_1_enemy" ],
        [ "Sample01_ObservableWWW", "class_uni_rx_1_1_examples_1_1_sample01___observable_w_w_w.html", null ],
        [ "Sample02_ObservableTriggers", "class_uni_rx_1_1_examples_1_1_sample02___observable_triggers.html", null ],
        [ "Sample03_GameObjectAsObservable", "class_uni_rx_1_1_examples_1_1_sample03___game_object_as_observable.html", null ],
        [ "Sample04_ConvertFromUnityCallback", "class_uni_rx_1_1_examples_1_1_sample04___convert_from_unity_callback.html", null ],
        [ "Sample05_ConvertFromCoroutine", "class_uni_rx_1_1_examples_1_1_sample05___convert_from_coroutine.html", null ],
        [ "Sample06_ConvertToCoroutine", "class_uni_rx_1_1_examples_1_1_sample06___convert_to_coroutine.html", null ],
        [ "Sample07_OrchestratIEnumerator", "class_uni_rx_1_1_examples_1_1_sample07___orchestrat_i_enumerator.html", null ],
        [ "Sample08_DetectDoubleClick", "class_uni_rx_1_1_examples_1_1_sample08___detect_double_click.html", null ],
        [ "Sample09_EventHandling", "class_uni_rx_1_1_examples_1_1_sample09___event_handling.html", "class_uni_rx_1_1_examples_1_1_sample09___event_handling" ],
        [ "Sample10_MainThreadDispatcher", "class_uni_rx_1_1_examples_1_1_sample10___main_thread_dispatcher.html", "class_uni_rx_1_1_examples_1_1_sample10___main_thread_dispatcher" ],
        [ "Sample11_Logger", "class_uni_rx_1_1_examples_1_1_sample11___logger.html", "class_uni_rx_1_1_examples_1_1_sample11___logger" ],
        [ "Sample12_ReactiveProperty", "class_uni_rx_1_1_examples_1_1_sample12___reactive_property.html", "class_uni_rx_1_1_examples_1_1_sample12___reactive_property" ],
        [ "Sample13_ToDoApp", "class_uni_rx_1_1_examples_1_1_sample13___to_do_app.html", "class_uni_rx_1_1_examples_1_1_sample13___to_do_app" ]
      ] ],
      [ "InternalUtil", "namespace_uni_rx_1_1_internal_util.html", [
        [ "DisposedObserver", "class_uni_rx_1_1_internal_util_1_1_disposed_observer.html", "class_uni_rx_1_1_internal_util_1_1_disposed_observer" ],
        [ "EmptyObserver", "class_uni_rx_1_1_internal_util_1_1_empty_observer.html", "class_uni_rx_1_1_internal_util_1_1_empty_observer" ],
        [ "ImmutableList", "class_uni_rx_1_1_internal_util_1_1_immutable_list.html", "class_uni_rx_1_1_internal_util_1_1_immutable_list" ],
        [ "ListObserver", "class_uni_rx_1_1_internal_util_1_1_list_observer.html", "class_uni_rx_1_1_internal_util_1_1_list_observer" ],
        [ "MicroCoroutine", "class_uni_rx_1_1_internal_util_1_1_micro_coroutine.html", "class_uni_rx_1_1_internal_util_1_1_micro_coroutine" ],
        [ "ThreadSafeQueueWorker", "class_uni_rx_1_1_internal_util_1_1_thread_safe_queue_worker.html", "class_uni_rx_1_1_internal_util_1_1_thread_safe_queue_worker" ],
        [ "ThrowObserver", "class_uni_rx_1_1_internal_util_1_1_throw_observer.html", "class_uni_rx_1_1_internal_util_1_1_throw_observer" ]
      ] ],
      [ "Operators", "namespace_uni_rx_1_1_operators.html", [
        [ "OperatorObservableBase", "class_uni_rx_1_1_operators_1_1_operator_observable_base.html", "class_uni_rx_1_1_operators_1_1_operator_observable_base" ],
        [ "OperatorObserverBase", "class_uni_rx_1_1_operators_1_1_operator_observer_base.html", "class_uni_rx_1_1_operators_1_1_operator_observer_base" ]
      ] ],
      [ "Triggers", "namespace_uni_rx_1_1_triggers.html", [
        [ "ObservableAnimatorTrigger", "class_uni_rx_1_1_triggers_1_1_observable_animator_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_animator_trigger" ],
        [ "ObservableBeginDragTrigger", "class_uni_rx_1_1_triggers_1_1_observable_begin_drag_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_begin_drag_trigger" ],
        [ "ObservableCancelTrigger", "class_uni_rx_1_1_triggers_1_1_observable_cancel_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_cancel_trigger" ],
        [ "ObservableCanvasGroupChangedTrigger", "class_uni_rx_1_1_triggers_1_1_observable_canvas_group_changed_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_canvas_group_changed_trigger" ],
        [ "ObservableCollision2DTrigger", "class_uni_rx_1_1_triggers_1_1_observable_collision2_d_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_collision2_d_trigger" ],
        [ "ObservableCollisionTrigger", "class_uni_rx_1_1_triggers_1_1_observable_collision_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_collision_trigger" ],
        [ "ObservableDeselectTrigger", "class_uni_rx_1_1_triggers_1_1_observable_deselect_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_deselect_trigger" ],
        [ "ObservableDestroyTrigger", "class_uni_rx_1_1_triggers_1_1_observable_destroy_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_destroy_trigger" ],
        [ "ObservableDragTrigger", "class_uni_rx_1_1_triggers_1_1_observable_drag_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_drag_trigger" ],
        [ "ObservableDropTrigger", "class_uni_rx_1_1_triggers_1_1_observable_drop_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_drop_trigger" ],
        [ "ObservableEnableTrigger", "class_uni_rx_1_1_triggers_1_1_observable_enable_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_enable_trigger" ],
        [ "ObservableEndDragTrigger", "class_uni_rx_1_1_triggers_1_1_observable_end_drag_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_end_drag_trigger" ],
        [ "ObservableEventTrigger", "class_uni_rx_1_1_triggers_1_1_observable_event_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_event_trigger" ],
        [ "ObservableFixedUpdateTrigger", "class_uni_rx_1_1_triggers_1_1_observable_fixed_update_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_fixed_update_trigger" ],
        [ "ObservableInitializePotentialDragTrigger", "class_uni_rx_1_1_triggers_1_1_observable_initialize_potential_drag_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_initialize_potential_drag_trigger" ],
        [ "ObservableJointTrigger", "class_uni_rx_1_1_triggers_1_1_observable_joint_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_joint_trigger" ],
        [ "ObservableLateUpdateTrigger", "class_uni_rx_1_1_triggers_1_1_observable_late_update_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_late_update_trigger" ],
        [ "ObservableMouseTrigger", "class_uni_rx_1_1_triggers_1_1_observable_mouse_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_mouse_trigger" ],
        [ "ObservableMoveTrigger", "class_uni_rx_1_1_triggers_1_1_observable_move_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_move_trigger" ],
        [ "ObservableParticleTrigger", "class_uni_rx_1_1_triggers_1_1_observable_particle_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_particle_trigger" ],
        [ "ObservablePointerClickTrigger", "class_uni_rx_1_1_triggers_1_1_observable_pointer_click_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_pointer_click_trigger" ],
        [ "ObservablePointerDownTrigger", "class_uni_rx_1_1_triggers_1_1_observable_pointer_down_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_pointer_down_trigger" ],
        [ "ObservablePointerEnterTrigger", "class_uni_rx_1_1_triggers_1_1_observable_pointer_enter_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_pointer_enter_trigger" ],
        [ "ObservablePointerExitTrigger", "class_uni_rx_1_1_triggers_1_1_observable_pointer_exit_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_pointer_exit_trigger" ],
        [ "ObservablePointerUpTrigger", "class_uni_rx_1_1_triggers_1_1_observable_pointer_up_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_pointer_up_trigger" ],
        [ "ObservableRectTransformTrigger", "class_uni_rx_1_1_triggers_1_1_observable_rect_transform_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_rect_transform_trigger" ],
        [ "ObservableScrollTrigger", "class_uni_rx_1_1_triggers_1_1_observable_scroll_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_scroll_trigger" ],
        [ "ObservableSelectTrigger", "class_uni_rx_1_1_triggers_1_1_observable_select_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_select_trigger" ],
        [ "ObservableStateMachineTrigger", "class_uni_rx_1_1_triggers_1_1_observable_state_machine_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_state_machine_trigger" ],
        [ "ObservableSubmitTrigger", "class_uni_rx_1_1_triggers_1_1_observable_submit_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_submit_trigger" ],
        [ "ObservableTransformChangedTrigger", "class_uni_rx_1_1_triggers_1_1_observable_transform_changed_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_transform_changed_trigger" ],
        [ "ObservableTrigger2DTrigger", "class_uni_rx_1_1_triggers_1_1_observable_trigger2_d_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_trigger2_d_trigger" ],
        [ "ObservableTriggerBase", "class_uni_rx_1_1_triggers_1_1_observable_trigger_base.html", "class_uni_rx_1_1_triggers_1_1_observable_trigger_base" ],
        [ "ObservableTriggerTrigger", "class_uni_rx_1_1_triggers_1_1_observable_trigger_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_trigger_trigger" ],
        [ "ObservableUpdateSelectedTrigger", "class_uni_rx_1_1_triggers_1_1_observable_update_selected_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_update_selected_trigger" ],
        [ "ObservableUpdateTrigger", "class_uni_rx_1_1_triggers_1_1_observable_update_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_update_trigger" ],
        [ "ObservableVisibleTrigger", "class_uni_rx_1_1_triggers_1_1_observable_visible_trigger.html", "class_uni_rx_1_1_triggers_1_1_observable_visible_trigger" ]
      ] ],
      [ "AnimationCurveReactiveProperty", "class_uni_rx_1_1_animation_curve_reactive_property.html", "class_uni_rx_1_1_animation_curve_reactive_property" ],
      [ "AsyncMessageBroker", "class_uni_rx_1_1_async_message_broker.html", "class_uni_rx_1_1_async_message_broker" ],
      [ "AsyncReactiveCommand", "class_uni_rx_1_1_async_reactive_command.html", "class_uni_rx_1_1_async_reactive_command" ],
      [ "AsyncSubject", "class_uni_rx_1_1_async_subject.html", "class_uni_rx_1_1_async_subject" ],
      [ "BehaviorSubject", "class_uni_rx_1_1_behavior_subject.html", "class_uni_rx_1_1_behavior_subject" ],
      [ "BooleanDisposable", "class_uni_rx_1_1_boolean_disposable.html", "class_uni_rx_1_1_boolean_disposable" ],
      [ "BooleanNotifier", "class_uni_rx_1_1_boolean_notifier.html", "class_uni_rx_1_1_boolean_notifier" ],
      [ "BoolReactiveProperty", "class_uni_rx_1_1_bool_reactive_property.html", "class_uni_rx_1_1_bool_reactive_property" ],
      [ "BoundsReactiveProperty", "class_uni_rx_1_1_bounds_reactive_property.html", "class_uni_rx_1_1_bounds_reactive_property" ],
      [ "ByteReactiveProperty", "class_uni_rx_1_1_byte_reactive_property.html", "class_uni_rx_1_1_byte_reactive_property" ],
      [ "CancellationToken", "struct_uni_rx_1_1_cancellation_token.html", "struct_uni_rx_1_1_cancellation_token" ],
      [ "CollectionAddEvent", "struct_uni_rx_1_1_collection_add_event.html", "struct_uni_rx_1_1_collection_add_event" ],
      [ "CollectionMoveEvent", "struct_uni_rx_1_1_collection_move_event.html", "struct_uni_rx_1_1_collection_move_event" ],
      [ "CollectionRemoveEvent", "struct_uni_rx_1_1_collection_remove_event.html", "struct_uni_rx_1_1_collection_remove_event" ],
      [ "CollectionReplaceEvent", "struct_uni_rx_1_1_collection_replace_event.html", "struct_uni_rx_1_1_collection_replace_event" ],
      [ "ColorReactiveProperty", "class_uni_rx_1_1_color_reactive_property.html", "class_uni_rx_1_1_color_reactive_property" ],
      [ "CompositeDisposable", "class_uni_rx_1_1_composite_disposable.html", "class_uni_rx_1_1_composite_disposable" ],
      [ "CountNotifier", "class_uni_rx_1_1_count_notifier.html", "class_uni_rx_1_1_count_notifier" ],
      [ "DictionaryAddEvent", "struct_uni_rx_1_1_dictionary_add_event.html", "struct_uni_rx_1_1_dictionary_add_event" ],
      [ "DictionaryDisposable", "class_uni_rx_1_1_dictionary_disposable.html", "class_uni_rx_1_1_dictionary_disposable" ],
      [ "DictionaryRemoveEvent", "struct_uni_rx_1_1_dictionary_remove_event.html", "struct_uni_rx_1_1_dictionary_remove_event" ],
      [ "DictionaryReplaceEvent", "struct_uni_rx_1_1_dictionary_replace_event.html", "struct_uni_rx_1_1_dictionary_replace_event" ],
      [ "DoubleReactiveProperty", "class_uni_rx_1_1_double_reactive_property.html", "class_uni_rx_1_1_double_reactive_property" ],
      [ "EventPattern", "class_uni_rx_1_1_event_pattern.html", "class_uni_rx_1_1_event_pattern" ],
      [ "FloatReactiveProperty", "class_uni_rx_1_1_float_reactive_property.html", "class_uni_rx_1_1_float_reactive_property" ],
      [ "FrameInterval", "struct_uni_rx_1_1_frame_interval.html", "struct_uni_rx_1_1_frame_interval" ],
      [ "IAsyncMessageBroker", "interface_uni_rx_1_1_i_async_message_broker.html", null ],
      [ "IAsyncMessagePublisher", "interface_uni_rx_1_1_i_async_message_publisher.html", "interface_uni_rx_1_1_i_async_message_publisher" ],
      [ "IAsyncMessageReceiver", "interface_uni_rx_1_1_i_async_message_receiver.html", "interface_uni_rx_1_1_i_async_message_receiver" ],
      [ "IAsyncReactiveCommand", "interface_uni_rx_1_1_i_async_reactive_command.html", "interface_uni_rx_1_1_i_async_reactive_command" ],
      [ "ICancelable", "interface_uni_rx_1_1_i_cancelable.html", "interface_uni_rx_1_1_i_cancelable" ],
      [ "IConnectableObservable", "interface_uni_rx_1_1_i_connectable_observable.html", "interface_uni_rx_1_1_i_connectable_observable" ],
      [ "IEventPattern", "interface_uni_rx_1_1_i_event_pattern.html", "interface_uni_rx_1_1_i_event_pattern" ],
      [ "IGroupedObservable", "interface_uni_rx_1_1_i_grouped_observable.html", "interface_uni_rx_1_1_i_grouped_observable" ],
      [ "IMessageBroker", "interface_uni_rx_1_1_i_message_broker.html", null ],
      [ "IMessagePublisher", "interface_uni_rx_1_1_i_message_publisher.html", "interface_uni_rx_1_1_i_message_publisher" ],
      [ "IMessageReceiver", "interface_uni_rx_1_1_i_message_receiver.html", "interface_uni_rx_1_1_i_message_receiver" ],
      [ "InspectorDisplayAttribute", "class_uni_rx_1_1_inspector_display_attribute.html", "class_uni_rx_1_1_inspector_display_attribute" ],
      [ "IntReactiveProperty", "class_uni_rx_1_1_int_reactive_property.html", "class_uni_rx_1_1_int_reactive_property" ],
      [ "IObservable", "interface_uni_rx_1_1_i_observable.html", "interface_uni_rx_1_1_i_observable" ],
      [ "IObserver", "interface_uni_rx_1_1_i_observer.html", "interface_uni_rx_1_1_i_observer" ],
      [ "IOptimizedObservable", "interface_uni_rx_1_1_i_optimized_observable.html", "interface_uni_rx_1_1_i_optimized_observable" ],
      [ "IProgress", "interface_uni_rx_1_1_i_progress.html", "interface_uni_rx_1_1_i_progress" ],
      [ "IReactiveCollection", "interface_uni_rx_1_1_i_reactive_collection.html", "interface_uni_rx_1_1_i_reactive_collection" ],
      [ "IReactiveCommand", "interface_uni_rx_1_1_i_reactive_command.html", "interface_uni_rx_1_1_i_reactive_command" ],
      [ "IReactiveDictionary", "interface_uni_rx_1_1_i_reactive_dictionary.html", null ],
      [ "IReactiveProperty", "interface_uni_rx_1_1_i_reactive_property.html", "interface_uni_rx_1_1_i_reactive_property" ],
      [ "IReadOnlyReactiveCollection", "interface_uni_rx_1_1_i_read_only_reactive_collection.html", "interface_uni_rx_1_1_i_read_only_reactive_collection" ],
      [ "IReadOnlyReactiveDictionary", "interface_uni_rx_1_1_i_read_only_reactive_dictionary.html", "interface_uni_rx_1_1_i_read_only_reactive_dictionary" ],
      [ "IReadOnlyReactiveProperty", "interface_uni_rx_1_1_i_read_only_reactive_property.html", "interface_uni_rx_1_1_i_read_only_reactive_property" ],
      [ "IScheduler", "interface_uni_rx_1_1_i_scheduler.html", "interface_uni_rx_1_1_i_scheduler" ],
      [ "ISchedulerLongRunning", "interface_uni_rx_1_1_i_scheduler_long_running.html", "interface_uni_rx_1_1_i_scheduler_long_running" ],
      [ "ISchedulerPeriodic", "interface_uni_rx_1_1_i_scheduler_periodic.html", "interface_uni_rx_1_1_i_scheduler_periodic" ],
      [ "ISchedulerQueueing", "interface_uni_rx_1_1_i_scheduler_queueing.html", "interface_uni_rx_1_1_i_scheduler_queueing" ],
      [ "IStructuralComparable", "interface_uni_rx_1_1_i_structural_comparable.html", "interface_uni_rx_1_1_i_structural_comparable" ],
      [ "IStructuralEquatable", "interface_uni_rx_1_1_i_structural_equatable.html", "interface_uni_rx_1_1_i_structural_equatable" ],
      [ "ISubject", "interface_uni_rx_1_1_i_subject.html", null ],
      [ "ITuple", "interface_uni_rx_1_1_i_tuple.html", "interface_uni_rx_1_1_i_tuple" ],
      [ "LongReactiveProperty", "class_uni_rx_1_1_long_reactive_property.html", "class_uni_rx_1_1_long_reactive_property" ],
      [ "MainThreadDispatcher", "class_uni_rx_1_1_main_thread_dispatcher.html", "class_uni_rx_1_1_main_thread_dispatcher" ],
      [ "MessageBroker", "class_uni_rx_1_1_message_broker.html", "class_uni_rx_1_1_message_broker" ],
      [ "MultilineReactivePropertyAttribute", "class_uni_rx_1_1_multiline_reactive_property_attribute.html", "class_uni_rx_1_1_multiline_reactive_property_attribute" ],
      [ "MultipleAssignmentDisposable", "class_uni_rx_1_1_multiple_assignment_disposable.html", "class_uni_rx_1_1_multiple_assignment_disposable" ],
      [ "Notification", "class_uni_rx_1_1_notification.html", "class_uni_rx_1_1_notification" ],
      [ "Observable", "class_uni_rx_1_1_observable.html", null ],
      [ "ObservableYieldInstruction", "class_uni_rx_1_1_observable_yield_instruction.html", "class_uni_rx_1_1_observable_yield_instruction" ],
      [ "Pair", "struct_uni_rx_1_1_pair.html", "struct_uni_rx_1_1_pair" ],
      [ "Progress", "class_uni_rx_1_1_progress.html", "class_uni_rx_1_1_progress" ],
      [ "QuaternionReactiveProperty", "class_uni_rx_1_1_quaternion_reactive_property.html", "class_uni_rx_1_1_quaternion_reactive_property" ],
      [ "RangeReactivePropertyAttribute", "class_uni_rx_1_1_range_reactive_property_attribute.html", "class_uni_rx_1_1_range_reactive_property_attribute" ],
      [ "ReactiveCollection", "class_uni_rx_1_1_reactive_collection.html", "class_uni_rx_1_1_reactive_collection" ],
      [ "ReactiveCommand", "class_uni_rx_1_1_reactive_command.html", "class_uni_rx_1_1_reactive_command" ],
      [ "ReactiveDictionary", "class_uni_rx_1_1_reactive_dictionary.html", "class_uni_rx_1_1_reactive_dictionary" ],
      [ "ReactiveProperty", "class_uni_rx_1_1_reactive_property.html", "class_uni_rx_1_1_reactive_property" ],
      [ "ReadOnlyReactiveProperty", "class_uni_rx_1_1_read_only_reactive_property.html", "class_uni_rx_1_1_read_only_reactive_property" ],
      [ "RectReactiveProperty", "class_uni_rx_1_1_rect_reactive_property.html", "class_uni_rx_1_1_rect_reactive_property" ],
      [ "RefCountDisposable", "class_uni_rx_1_1_ref_count_disposable.html", "class_uni_rx_1_1_ref_count_disposable" ],
      [ "ReplaySubject", "class_uni_rx_1_1_replay_subject.html", "class_uni_rx_1_1_replay_subject" ],
      [ "ScheduledDisposable", "class_uni_rx_1_1_scheduled_disposable.html", "class_uni_rx_1_1_scheduled_disposable" ],
      [ "ScheduledNotifier", "class_uni_rx_1_1_scheduled_notifier.html", "class_uni_rx_1_1_scheduled_notifier" ],
      [ "SerialDisposable", "class_uni_rx_1_1_serial_disposable.html", "class_uni_rx_1_1_serial_disposable" ],
      [ "SingleAssignmentDisposable", "class_uni_rx_1_1_single_assignment_disposable.html", "class_uni_rx_1_1_single_assignment_disposable" ],
      [ "StableCompositeDisposable", "class_uni_rx_1_1_stable_composite_disposable.html", "class_uni_rx_1_1_stable_composite_disposable" ],
      [ "StringReactiveProperty", "class_uni_rx_1_1_string_reactive_property.html", "class_uni_rx_1_1_string_reactive_property" ],
      [ "Subject", "class_uni_rx_1_1_subject.html", "class_uni_rx_1_1_subject" ],
      [ "TimeInterval", "struct_uni_rx_1_1_time_interval.html", "struct_uni_rx_1_1_time_interval" ],
      [ "Timestamped", "struct_uni_rx_1_1_timestamped.html", "struct_uni_rx_1_1_timestamped" ],
      [ "Tuple", "class_uni_rx_1_1_tuple.html", "class_uni_rx_1_1_tuple" ],
      [ "Unit", "struct_uni_rx_1_1_unit.html", "struct_uni_rx_1_1_unit" ],
      [ "Vector2ReactiveProperty", "class_uni_rx_1_1_vector2_reactive_property.html", "class_uni_rx_1_1_vector2_reactive_property" ],
      [ "Vector3ReactiveProperty", "class_uni_rx_1_1_vector3_reactive_property.html", "class_uni_rx_1_1_vector3_reactive_property" ],
      [ "Vector4ReactiveProperty", "class_uni_rx_1_1_vector4_reactive_property.html", "class_uni_rx_1_1_vector4_reactive_property" ],
      [ "WWWErrorException", "class_uni_rx_1_1_w_w_w_error_exception.html", "class_uni_rx_1_1_w_w_w_error_exception" ]
    ] ],
    [ "UniRxExtension", "namespace_uni_rx_extension.html", [
      [ "ReactiveList", "class_uni_rx_extension_1_1_reactive_list.html", "class_uni_rx_extension_1_1_reactive_list" ],
      [ "ReactiveListNameSafe", "class_uni_rx_extension_1_1_reactive_list_name_safe.html", "class_uni_rx_extension_1_1_reactive_list_name_safe" ]
    ] ],
    [ "UnitTests", "namespace_unit_tests.html", [
      [ "Models", "namespace_unit_tests_1_1_models.html", [
        [ "Considerations", "namespace_unit_tests_1_1_models_1_1_considerations.html", [
          [ "UT_Consideration", "class_unit_tests_1_1_models_1_1_considerations_1_1_u_t___consideration.html", "class_unit_tests_1_1_models_1_1_considerations_1_1_u_t___consideration" ],
          [ "UT_DoNotRepeat", "class_unit_tests_1_1_models_1_1_considerations_1_1_u_t___do_not_repeat.html", "class_unit_tests_1_1_models_1_1_considerations_1_1_u_t___do_not_repeat" ],
          [ "UT_FixedValue", "class_unit_tests_1_1_models_1_1_considerations_1_1_u_t___fixed_value.html", "class_unit_tests_1_1_models_1_1_considerations_1_1_u_t___fixed_value" ],
          [ "UT_RandomValue", "class_unit_tests_1_1_models_1_1_considerations_1_1_u_t___random_value.html", "class_unit_tests_1_1_models_1_1_considerations_1_1_u_t___random_value" ]
        ] ],
        [ "Error", "namespace_unit_tests_1_1_models_1_1_error.html", [
          [ "UT_ErrorConsideration", "class_unit_tests_1_1_models_1_1_error_1_1_u_t___error_consideration.html", "class_unit_tests_1_1_models_1_1_error_1_1_u_t___error_consideration" ],
          [ "UT_ErrorResponseFunction", "class_unit_tests_1_1_models_1_1_error_1_1_u_t___error_response_function.html", "class_unit_tests_1_1_models_1_1_error_1_1_u_t___error_response_function" ]
        ] ],
        [ "ResponseFunctions", "namespace_unit_tests_1_1_models_1_1_response_functions.html", [
          [ "UT_BoolFunction", "class_unit_tests_1_1_models_1_1_response_functions_1_1_u_t___bool_function.html", "class_unit_tests_1_1_models_1_1_response_functions_1_1_u_t___bool_function" ],
          [ "UT_ExponentialFunction", "class_unit_tests_1_1_models_1_1_response_functions_1_1_u_t___exponential_function.html", "class_unit_tests_1_1_models_1_1_response_functions_1_1_u_t___exponential_function" ],
          [ "UT_FixedValueFunction", "class_unit_tests_1_1_models_1_1_response_functions_1_1_u_t___fixed_value_function.html", "class_unit_tests_1_1_models_1_1_response_functions_1_1_u_t___fixed_value_function" ],
          [ "UT_InverseLogistic", "class_unit_tests_1_1_models_1_1_response_functions_1_1_u_t___inverse_logistic.html", "class_unit_tests_1_1_models_1_1_response_functions_1_1_u_t___inverse_logistic" ]
        ] ],
        [ "UT_Agent", "class_unit_tests_1_1_models_1_1_u_t___agent.html", "class_unit_tests_1_1_models_1_1_u_t___agent" ],
        [ "UT_AgentAction", "class_unit_tests_1_1_models_1_1_u_t___agent_action.html", "class_unit_tests_1_1_models_1_1_u_t___agent_action" ],
        [ "UT_AiContext", "class_unit_tests_1_1_models_1_1_u_t___ai_context.html", "class_unit_tests_1_1_models_1_1_u_t___ai_context" ],
        [ "UT_InfoModel", "class_unit_tests_1_1_models_1_1_u_t___info_model.html", "class_unit_tests_1_1_models_1_1_u_t___info_model" ],
        [ "UT_Parameter", "class_unit_tests_1_1_models_1_1_u_t___parameter.html", "class_unit_tests_1_1_models_1_1_u_t___parameter" ],
        [ "UT_ParameterEnum", "class_unit_tests_1_1_models_1_1_u_t___parameter_enum.html", "class_unit_tests_1_1_models_1_1_u_t___parameter_enum" ],
        [ "UT_ProjectSettingsModel", "class_unit_tests_1_1_models_1_1_u_t___project_settings_model.html", "class_unit_tests_1_1_models_1_1_u_t___project_settings_model" ],
        [ "UT_ResponseCurve", "class_unit_tests_1_1_models_1_1_u_t___response_curve.html", "class_unit_tests_1_1_models_1_1_u_t___response_curve" ]
      ] ],
      [ "Scorers", "namespace_unit_tests_1_1_scorers.html", [
        [ "DecisionScoreEvaluators", "namespace_unit_tests_1_1_scorers_1_1_decision_score_evaluators.html", [
          [ "UtDecisionScoreEvaluator", "class_unit_tests_1_1_scorers_1_1_decision_score_evaluators_1_1_ut_decision_score_evaluator.html", "class_unit_tests_1_1_scorers_1_1_decision_score_evaluators_1_1_ut_decision_score_evaluator" ]
        ] ],
        [ "UtilityContainerSelectors", "namespace_unit_tests_1_1_scorers_1_1_utility_container_selectors.html", [
          [ "UT_UCSHighestScore", "class_unit_tests_1_1_scorers_1_1_utility_container_selectors_1_1_u_t___u_c_s_highest_score.html", "class_unit_tests_1_1_scorers_1_1_utility_container_selectors_1_1_u_t___u_c_s_highest_score" ]
        ] ],
        [ "UtilityScorers", "namespace_unit_tests_1_1_scorers_1_1_utility_scorers.html", [
          [ "UT_UsAverageScorer", "class_unit_tests_1_1_scorers_1_1_utility_scorers_1_1_u_t___us_average_scorer.html", "class_unit_tests_1_1_scorers_1_1_utility_scorers_1_1_u_t___us_average_scorer" ]
        ] ],
        [ "UT_ScorerService", "class_unit_tests_1_1_scorers_1_1_u_t___scorer_service.html", "class_unit_tests_1_1_scorers_1_1_u_t___scorer_service" ]
      ] ],
      [ "Services", "namespace_unit_tests_1_1_services.html", [
        [ "UT_AgentManager", "class_unit_tests_1_1_services_1_1_u_t___agent_manager.html", "class_unit_tests_1_1_services_1_1_u_t___agent_manager" ],
        [ "UT_ErrorObjectService", "class_unit_tests_1_1_services_1_1_u_t___error_object_service.html", "class_unit_tests_1_1_services_1_1_u_t___error_object_service" ],
        [ "UT_FileExtensionService", "class_unit_tests_1_1_services_1_1_u_t___file_extension_service.html", "class_unit_tests_1_1_services_1_1_u_t___file_extension_service" ],
        [ "UT_JsonPersister", "class_unit_tests_1_1_services_1_1_u_t___json_persister.html", "class_unit_tests_1_1_services_1_1_u_t___json_persister" ],
        [ "UT_PathService", "class_unit_tests_1_1_services_1_1_u_t___path_service.html", "class_unit_tests_1_1_services_1_1_u_t___path_service" ],
        [ "UT_RestoreAbleService", "class_unit_tests_1_1_services_1_1_u_t___restore_able_service.html", "class_unit_tests_1_1_services_1_1_u_t___restore_able_service" ]
      ] ]
    ] ],
    [ "UnityGuidRegenerator", "namespace_unity_guid_regenerator.html", [
      [ "UnityGuidRegeneratorMenu", "class_unity_guid_regenerator_1_1_unity_guid_regenerator_menu.html", null ]
    ] ],
    [ "AgentAction", "class_agent_action.html", "class_agent_action" ],
    [ "AgentActionState", "class_agent_action_state.html", "class_agent_action_state" ],
    [ "AgentModel", "class_agent_model.html", "class_agent_model" ],
    [ "AgentMono", "class_agent_mono.html", "class_agent_mono" ],
    [ "AgentScript", "class_agent_script.html", "class_agent_script" ],
    [ "AiContext", "class_ai_context.html", "class_ai_context" ],
    [ "AiObjectModel", "class_ai_object_model.html", "class_ai_object_model" ],
    [ "AiObjectState", "class_ai_object_state.html", "class_ai_object_state" ],
    [ "Bucket", "class_bucket.html", "class_bucket" ],
    [ "BucketState", "class_bucket_state.html", "class_bucket_state" ],
    [ "ButtonPopUpWindow", "class_button_pop_up_window.html", "class_button_pop_up_window" ],
    [ "CollectionViewModel", "class_collection_view_model.html", "class_collection_view_model" ],
    [ "Consideration", "class_consideration.html", "class_consideration" ],
    [ "ConsiderationBoolean", "class_consideration_boolean.html", "class_consideration_boolean" ],
    [ "ConsiderationModifier", "class_consideration_modifier.html", "class_consideration_modifier" ],
    [ "ConsiderationState", "class_consideration_state.html", "class_consideration_state" ],
    [ "ContextAddress", "class_context_address.html", "class_context_address" ],
    [ "Decision", "class_decision.html", "class_decision" ],
    [ "DecisionScoreEvaluator", "class_decision_score_evaluator.html", "class_decision_score_evaluator" ],
    [ "DecisionState", "class_decision_state.html", "class_decision_state" ],
    [ "Demo_ConsiderationBoolean", "class_demo___consideration_boolean.html", "class_demo___consideration_boolean" ],
    [ "DropdownDescriptionViewModel", "class_dropdown_description_view_model.html", "class_dropdown_description_view_model" ],
    [ "EditorGraph", "class_editor_graph.html", "class_editor_graph" ],
    [ "ExponentialFunction", "class_exponential_function.html", "class_exponential_function" ],
    [ "FileComparer", "class_file_comparer.html", "class_file_comparer" ],
    [ "FoldableComponent", "class_foldable_component.html", "class_foldable_component" ],
    [ "IAgent", "interface_i_agent.html", "interface_i_agent" ],
    [ "IAiContext", "interface_i_ai_context.html", "interface_i_ai_context" ],
    [ "IDecisionScoreEvaluator", "interface_i_decision_score_evaluator.html", "interface_i_decision_score_evaluator" ],
    [ "IIdentifier", "interface_i_identifier.html", "interface_i_identifier" ],
    [ "InspectorView", "class_inspector_view.html", "class_inspector_view" ],
    [ "IntegerFieldMinMax", "class_integer_field_min_max.html", "class_integer_field_min_max" ],
    [ "InverseLogisticFunction", "class_inverse_logistic_function.html", "class_inverse_logistic_function" ],
    [ "IPersister", "interface_i_persister.html", "interface_i_persister" ],
    [ "IUtilityScorer", "interface_i_utility_scorer.html", "interface_i_utility_scorer" ],
    [ "LinearFunction", "class_linear_function.html", "class_linear_function" ],
    [ "LineChartComponentOld", "class_line_chart_component_old.html", "class_line_chart_component_old" ],
    [ "ListViewModel", "class_list_view_model.html", "class_list_view_model" ],
    [ "LogisticFunction", "class_logistic_function.html", "class_logistic_function" ],
    [ "ObjectMetaData", "class_object_meta_data.html", "class_object_meta_data" ],
    [ "PanelSelection", "class_panel_selection.html", "class_panel_selection" ],
    [ "Parameter", "class_parameter.html", "class_parameter" ],
    [ "ParameterComponent", "class_parameter_component.html", "class_parameter_component" ],
    [ "ParameterContainer", "class_parameter_container.html", "class_parameter_container" ],
    [ "ParameterContainerState", "class_parameter_container_state.html", "class_parameter_container_state" ],
    [ "ParameterEnum", "class_parameter_enum.html", "class_parameter_enum" ],
    [ "ParameterEnumState", "class_parameter_enum_state.html", "class_parameter_enum_state" ],
    [ "ParameterState", "class_parameter_state.html", "class_parameter_state" ],
    [ "PathService", "class_path_service.html", null ],
    [ "PlayAbleAiService", "class_play_able_ai_service.html", "class_play_able_ai_service" ],
    [ "PlayAbleAiServiceState", "class_play_able_ai_service_state.html", "class_play_able_ai_service_state" ],
    [ "PopUpService", "class_pop_up_service.html", null ],
    [ "ResponseCurve", "class_response_curve.html", "class_response_curve" ],
    [ "ResponseCurveMinimizedViewModel", "class_response_curve_minimized_view_model.html", "class_response_curve_minimized_view_model" ],
    [ "ResponseCurveState", "class_response_curve_state.html", "class_response_curve_state" ],
    [ "ResponseFunction", "class_response_function.html", "class_response_function" ],
    [ "ResponseFunctionState", "class_response_function_state.html", "class_response_function_state" ],
    [ "RestoreAble", "class_restore_able.html", "class_restore_able" ],
    [ "RestoreState", "class_restore_state.html", "class_restore_state" ],
    [ "ScoreModel", "class_score_model.html", "class_score_model" ],
    [ "ScorerService", "class_scorer_service.html", "class_scorer_service" ],
    [ "ScoreViewModel", "class_score_view_model.html", "class_score_view_model" ],
    [ "SplitView", "class_split_view.html", "class_split_view" ],
    [ "TickerMode", "class_ticker_mode.html", "class_ticker_mode" ],
    [ "TickerModeState", "class_ticker_mode_state.html", "class_ticker_mode_state" ],
    [ "TickMetaData", "class_tick_meta_data.html", "class_tick_meta_data" ],
    [ "Uai", "class_uai.html", "class_uai" ],
    [ "UaiState", "class_uai_state.html", "class_uai_state" ],
    [ "UaiTickerSettingsModel", "class_uai_ticker_settings_model.html", "class_uai_ticker_settings_model" ],
    [ "UaiTickerSettingsModelState", "class_uai_ticker_settings_model_state.html", "class_uai_ticker_settings_model_state" ],
    [ "UasTemplateServiceState", "class_uas_template_service_state.html", "class_uas_template_service_state" ],
    [ "UCSHighestScore", "class_u_c_s_highest_score.html", "class_u_c_s_highest_score" ],
    [ "UsAverageScorer", "class_us_average_scorer.html", "class_us_average_scorer" ],
    [ "USCompensationScorer", "class_u_s_compensation_scorer.html", "class_u_s_compensation_scorer" ],
    [ "UtilityContainer", "class_utility_container.html", "class_utility_container" ],
    [ "UtilityContainerSelector", "class_utility_container_selector.html", "class_utility_container_selector" ],
    [ "UtilityContainerSelectorState", "class_utility_container_selector_state.html", "class_utility_container_selector_state" ]
];