@startwbs
'https://plantuml.com/wbs-diagram
title Component tree of Ai Objects

+ AI
-- Bucket 1
--- C...
+++ D...
** Bucket X
--- Consideration 1
--- ...
--- Consideration N
---- Parameter 1
---- ...
---- Parameter N
**** Response Curve
***** Response Function 1
***** ...
***** Response Function N
+++ Decision 1
+++ ...
+++ Decision N
---- Consideration 1
---- ...
---- Consideration N
----- Parameter 1
----- ...
----- Parameter N
***** Response Curve
****** Response Function 1
****** ...
****** Response Function N
++++ AgentAction 1
++++ ...
++++ AgentAction N
***** Parameter 1
***** ...
***** Parameter N
++ Bucket N
--- C...
+++ D...
@endwbs